### PR TITLE
Fix single quote quotation

### PR DESCRIPTION
**Pull request by GerardRodes**

### CODE REVIEW

**Review by gustavohmsilva — APPROVED** [review]
LGTM. Although it is weird to have one case with two conditional tests.

**Comment by arp242** [comment]
According to RFC5322 only `"` is a valid quotation character.

**Comment by GerardRodes** [comment]
> According to RFC5322 only `"` is a valid quotation character. A `'` is just a literal.

We have the following on a customer email
```
To: 'Foo Bar' <foo@bar.com>; var@var.com
```
and also
```
>To: 'var@var.com'
```

This email client is quoting with single quotes

---

We have to treat `'` as a quotation character on this package or remove `'` characters up on the desk pkg making use of `mailaddress` since we don't want the name of the customer to appear quoted by `'`

**Comment by arp242** [comment]
I figured as much, but that's basically wrong. Practicality beats purity, but I'd be real careful just changing this based on a single customer/example, as some email clients may use a literal `'` and it may end up breaking more than it fixes.

You can do what you want, I haven't even worked at Teamwork for years, but personally I'd be really careful with this. For example I just tested from FastMail, and it just sends:

    To: a'b <martin@arp242.net>

A `'` is somewhat common-ish in names, so it's not inconceivable it's set.

A better way might be to treat `'` as a quotation character only if it starts and ends with it. That is, leave the loop as-is and after it do something like `if strings.HasPrefix(addr.Name, `'`) && strings.HasSuffix(addr.Name, "'") { strings.Trim(addr.Name, "'") }`. The case `'Martin' foo 'Tournoij'` probably doesn't need to be supported(?)

**Comment by GerardRodes** [comment]
> I figured as much, but that's basically wrong. Practicality beats purity, but I'd be real careful just changing this based on a single customer/example, as some email clients may use a literal `'` and it may end up breaking more than it fixes.
> 
> You can do what you want, I haven't even worked at Teamwork for years, but personally I'd be really careful with this. For example I just tested from FastMail, and it just sends:
> 
> ```
> To: a'b <martin@arp242.net>
> ```
> 
> A `'` is somewhat common-ish in names, so it's not inconceivable it's set.
> 
> A better way might be to treat `'` as a quotation character only if it starts and ends with it. That is, leave the loop as-is and after it do something like `if strings.HasPrefix(addr.Name, `'`) && strings.HasSuffix(addr.Name, "'") { strings.Trim(addr.Name, "'") }`. The case `'Martin' foo 'Tournoij'` probably doesn't need to be supported(?)

You are right, good catch

**Comment by GerardRodes** [comment]
Updated it, now only will remove wrapping `'` if there are no other `'` in the middle of the name

**Pull request merged**
